# Serverless Limit Monitor Solution
#
# template for serverless-limit-monitor-solution
# **DO NOT DELETE**
#
# author: aws-solutions-builder@
AWSTemplateFormatVersion: 2010-09-09

Description: (SO0668) - Solution - Master Template

Parameters:
  # Sample parameter 1
  Param1:
    Description: Parameter 1.
    Type: String

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Section 1
      Parameters:
      - Param1
    ParameterLabels:
      Param1:
        default: Parameter #1

Mappings:
  MetricsMap:
    Send-Data:
      SendAnonymousData: "Yes"

  SourceCode:
    General:
      S3Bucket: %%BUCKET_NAME%%
      KeyPrefix: "%%SOLUTION_NAME%%/%%VERSION%%"

Resources:
  #
  # Hello Function
  # [HelloFunction, HelloFunctionRole]
  #
  HelloFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: Example Solution - Lambda function to send greetings
      Environment:
        Variables:
          LOG_LEVEL: 'INFO' # change to WARN, ERROR or DEBUG as needed
      Handler: index.handler
      Role: !Sub ${HelloFunctionRole.Arn}
      Code:
        S3Bucket: !Join ["-", [!FindInMap ["SourceCode", "General", "S3Bucket"], Ref: "AWS::Region"]]
        S3Key: !Join ["/", [!FindInMap ["SourceCode", "General", "KeyPrefix"],  "example-function-js.zip"]]
      Runtime: nodejs8.10
      Timeout: 300


            
Outputs:
            
