name: scheduled-workflow

on:
  workflow_dispatch:

jobs:
  build-us-west-2:
    runs-on: ubuntu-latest
    steps:
      - name: Check out development branch
        uses: actions/checkout@v2.3.4
        with:
          ref: development

      - name: Initialize AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Generate short sha
        run: |
          echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
      - name: Run build script
        run: |
          cd deployment
          SFM_STACK_NAME=sfm-dev
          REGION=us-west-2
          VERSION=$SHORT_SHA
          DIST_OUTPUT_BUCKET=sfm-dev
          TEMPLATE_OUTPUT_BUCKET=sfm-dev-us-west-2
          ./build-s3-dist.sh --template-bucket $TEMPLATE_OUTPUT_BUCKET --code-bucket $DIST_OUTPUT_BUCKET --version $VERSION --region $REGION
          aws cloudformation deploy --stack-name $SFM_STACK_NAME --region $REGION --template-file global-s3-assets/simple-file-manager-for-amazon-efs.template --s3-bucket $DIST_OUTPUT_BUCKET-$REGION --s3-prefix efs_file_manager/$VERSION --parameter-overrides AdminEmail=${{ secrets.TEST_ADMIN_EMAIL }} --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --force-upload
      - name: Build Failed
        if: ${{ failure() }}
        uses: nashmaniac/create-issue-action@v1.1
        with:
          title: Nightly build failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: brandold
          labels: bug
          body: Nightly build failed for commit ${{github.sha}}


  test-us-west-2:
    needs: build-us-west-2
    runs-on: ubuntu-latest
    env:
      SFM_REGION: 'us-west-2'
      SFM_STACK_NAME: sfm-dev
    steps:
      - name: Check out development branch
        uses: actions/checkout@v2.3.4
        with:
          ref: development
      - name: Initialize build AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Generate short sha
        run: |
          echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
      - name: Run cfn_nag
        uses: stelligent/cfn_nag@master
        continue-on-error: true
        with:
          input_path: deployment
      - name: Setup Chromedriver
        uses: nanasess/setup-chromedriver@master
      - name: Get user pool id
        run: |
          echo "USER_POOL_ID=`aws cloudformation describe-stacks --query 'Stacks[?starts_with(StackName, \`sfm-dev-EFSFileAuthentication\`)].Outputs[1].OutputValue' --output text`" >> $GITHUB_ENV
      - name: Reset SFM user password
        run: |
          aws cognito-idp admin-set-user-password --user-pool-id $USER_POOL_ID --username ${{ secrets.TEST_ADMIN_EMAIL }} --password ${{ secrets.TEST_ADMIN_PASSWORD }} --permanent
      - name: Get SFM endpoint
        run: |
          echo "SFM_ENDPOINT=`aws cloudformation describe-stacks --query 'Stacks[?starts_with(StackName, \`sfm-dev-EFSFileWebApplication\`)].Outputs[0].OutputValue' --output text`" >> $GITHUB_ENV
      - name: Set admin creds
        run: |
          echo SFM_USERNAME=${{ secrets.TEST_ADMIN_EMAIL }} >> $GITHUB_ENV
          echo SFM_PASSWORD=${{ secrets.TEST_ADMIN_PASSWORD }} >> $GITHUB_ENV
      - name: Set media path and file name
        run: |
          echo TEST_MEDIA_PATH=$GITHUB_WORKSPACE/test/e2e/ >> $GITHUB_ENV
          echo TEST_FILE_NAME=run_e2e.sh >> $GITHUB_ENV
      - name: Set filesystem id
        run: |
          echo FILESYSTEM_ID=${{ secrets.TEST_FILESYSEM_ID }} >> $GITHUB_ENV
      - name: Run E2E tests
        run: |
          cd $GITHUB_WORKSPACE
          cd test/e2e
          ./run_e2e.sh
      - name: Test Failed
        if: ${{ failure() }}
        uses: nashmaniac/create-issue-action@v1.1
        with:
          title: Nightly test for failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: brandold
          labels: bug
          body: Nightly test failed for commit ${{github.sha}}
      - name: Delete stack
        run: |
          aws cloudformation delete-stack --stack-name $SFM_STACK_NAME
