name: scheduled-workflow

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  build-us-west-2:
    runs-on: ubuntu-latest
    steps:
      - name: Check out development branch
        uses: actions/checkout@v2.3.4
        with:
          ref: development

      - name: Initialize AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Generate short sha
        run: |
          echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
      - name: Run build script
        run: |
          cd deployment
          SFM_STACK_NAME=sfm-dev
          REGION=us-west-2
          VERSION=$SHORT_SHA
          DIST_OUTPUT_BUCKET=sfm-dev
          TEMPLATE_OUTPUT_BUCKET=sfm-dev-us-west-2
          ./build-s3-dist.sh --no-layer --template-bucket $TEMPLATE_OUTPUT_BUCKET --code-bucket $DIST_OUTPUT_BUCKET --version $VERSION --region $REGION
          aws cloudformation deploy --stack-name $SFM_STACK_NAME --region $REGION --template-file global-s3-assets/efs-file-manager.template --s3-bucket $DIST_OUTPUT_BUCKET-$REGION --s3-prefix efs_file_manager/$VERSION --parameter-overrides AdminEmail=brandold@amazon.com --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --force-upload
      - name: Build Failed
        if: ${{ failure() }}
        uses: nashmaniac/create-issue-action@v1.1
        with:
          title: Nightly build for $SHORT_SHA Failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: brandold
          labels: bug
          body: Nightly build failed for commit ${{github.sha}}


  test-us-west-2:
    needs: build-us-west-2
    runs-on: ubuntu-latest
    env:
      SFM_REGION: 'us-west-2'
      SFM_STACK_NAME: sfm-dev
    steps:
      - name: Check out development branch
        uses: actions/checkout@v2.3.4
        with:
          ref: development
      - name: Initialize build AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Generate short sha
        run: |
          echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
      - name: Run cfn_nag
        uses: stelligent/cfn_nag@master
        continue-on-error: true
        with:
          input_path: deployment
      - name: Setup Chromedriver
        uses: nanasess/setup-chromedriver@master
      - name: Get user pool id
        run: |
          echo "USER_POOL_ID=`aws cloudformation describe-stacks --query 'Stacks[?starts_with(StackName, \`sfm-dev-EFSFileAuthentication\`)].Outputs[1].OutputValue' --output text`" >> $GITHUB_ENV
      - name: Reset SFM user password
        run: |
          aws cognito-idp admin-set-user-password --user-pool-id $USER_POOL_ID --username "brandondold@gmail.com" --password ${{ secrets.TEMP_PASSWORD }} --permanent
      - name: Run E2E tests
        run: |
          cd $GITHUB_WORKSPACE
          cd test/e2e
          ./run_e2e.sh
      - name: Test Failed
        if: ${{ failure() }}
        uses: nashmaniac/create-issue-action@v1.1
        with:
          title: Nightly test for $SHORT_SHA Failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: brandold
          labels: bug
          body: Nightly test failed for commit ${{github.sha}}
      - name: Delete stack
        run: |
          aws cloudformation delete-stack --stack-name $SFM_STACK_NAME